package com.momentum.hierarchy.output;

import com.momentum.hierarchy.employee.EmployeeRecord;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * HTML formatter for organization hierarchy.
 * Generates a beautiful, interactive HTML page with modern styling.
 */
public class HTMLFormatter implements HierarchyFormatter {
    
    @Override
    public String format(Map<String, List<EmployeeRecord>> hierarchyTree, 
                        List<EmployeeRecord> allEmployees, 
                        EmployeeRecord ceo) {
        
        // Create employee map for quick lookup
        Map<String, EmployeeRecord> employeeMap = allEmployees.stream()
                .collect(Collectors.toMap(EmployeeRecord::getID, employee -> employee));
        
        StringBuilder html = new StringBuilder();
        
        // HTML header with modern styling
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"en\">\n");
        html.append("<head>\n");
        html.append("    <meta charset=\"UTF-8\">\n");
        html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("    <title>Organization Hierarchy</title>\n");
        html.append("    <style>\n");
        html.append("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
        html.append("        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }\n");
        html.append("        .container { max-width: 1200px; margin: 0 auto; background: white; border-radius: 15px; box-shadow: 0 20px 40px rgba(0,0,0,0.1); overflow: hidden; }\n");
        html.append("        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }\n");
        html.append("        .header h1 { font-size: 2.5em; margin-bottom: 10px; }\n");
        html.append("        .header p { font-size: 1.2em; opacity: 0.9; }\n");
        html.append("        .summary { background: #f8f9fa; padding: 20px; border-bottom: 1px solid #e9ecef; }\n");
        html.append("        .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; }\n");
        html.append("        .summary-item { background: white; padding: 15px; border-radius: 10px; text-align: center; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\n");
        html.append("        .summary-item h3 { color: #667eea; margin-bottom: 5px; }\n");
        html.append("        .summary-item p { font-size: 1.5em; font-weight: bold; color: #333; }\n");
        html.append("        .hierarchy { padding: 30px; }\n");
        html.append("        .hierarchy h2 { color: #333; margin-bottom: 20px; font-size: 1.8em; }\n");
        html.append("        .tree { font-family: 'Courier New', monospace; }\n");
        html.append("        .employee { margin: 5px 0; padding: 10px; border-radius: 8px; background: #f8f9fa; border-left: 4px solid #667eea; transition: all 0.3s ease; }\n");
        html.append("        .employee:hover { background: #e3f2fd; transform: translateX(5px); }\n");
        html.append("        .employee-name { font-weight: bold; color: #333; }\n");
        html.append("        .employee-id { color: #666; font-size: 0.9em; }\n");
        html.append("        .level-0 { margin-left: 0px; }\n");
        html.append("        .level-1 { margin-left: 30px; }\n");
        html.append("        .level-2 { margin-left: 60px; }\n");
        html.append("        .level-3 { margin-left: 90px; }\n");
        html.append("        .level-4 { margin-left: 120px; }\n");
        html.append("        .level-5 { margin-left: 150px; }\n");
        html.append("        .ceo-badge { background: #ff6b6b; color: white; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; margin-left: 10px; }\n");
        html.append("        .manager-badge { background: #4ecdc4; color: white; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; margin-left: 10px; }\n");
        html.append("        .footer { background: #333; color: white; text-align: center; padding: 20px; }\n");
        html.append("        .footer p { opacity: 0.8; }\n");
        html.append("        @media (max-width: 768px) { .container { margin: 10px; } .header h1 { font-size: 2em; } }\n");
        html.append("    </style>\n");
        html.append("</head>\n");
        html.append("<body>\n");
        
        // Header
        html.append("    <div class=\"container\">\n");
        html.append("        <div class=\"header\">\n");
        html.append("            <h1>🏢 Organization Hierarchy</h1>\n");
        html.append("            <p>Generated by Organization Hierarchy Application</p>\n");
        html.append("        </div>\n");
        
        // Summary section
        html.append("        <div class=\"summary\">\n");
        html.append("            <div class=\"summary-grid\">\n");
        html.append("                <div class=\"summary-item\">\n");
        html.append("                    <h3>Total Employees</h3>\n");
        html.append("                    <p>").append(allEmployees.size()).append("</p>\n");
        html.append("                </div>\n");
        html.append("                <div class=\"summary-item\">\n");
        html.append("                    <h3>CEO</h3>\n");
        html.append("                    <p>").append(ceo.getName()).append("</p>\n");
        html.append("                </div>\n");
        html.append("                <div class=\"summary-item\">\n");
        html.append("                    <h3>CEO ID</h3>\n");
        html.append("                    <p>").append(ceo.getID()).append("</p>\n");
        html.append("                </div>\n");
        html.append("                <div class=\"summary-item\">\n");
        html.append("                    <h3>Hierarchy Levels</h3>\n");
        html.append("                    <p>").append(calculateMaxLevel(hierarchyTree, ceo.getID())).append("</p>\n");
        html.append("                </div>\n");
        html.append("            </div>\n");
        html.append("        </div>\n");
        
        // Hierarchy section
        html.append("        <div class=\"hierarchy\">\n");
        html.append("            <h2>📊 Organization Structure</h2>\n");
        html.append("            <div class=\"tree\">\n");
        
        // Generate hierarchy tree
        generateHierarchyHTML(hierarchyTree, ceo.getID(), 0, html, employeeMap);
        
        html.append("            </div>\n");
        html.append("        </div>\n");
        
        // Footer
        html.append("        <div class=\"footer\">\n");
        html.append("            <p>Generated on ").append(java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append("</p>\n");
        html.append("        </div>\n");
        html.append("    </div>\n");
        
        html.append("</body>\n");
        html.append("</html>");
        
        return html.toString();
    }
    
    private void generateHierarchyHTML(Map<String, List<EmployeeRecord>> hierarchyTree, 
                                     String employeeId, int level, StringBuilder html,
                                     Map<String, EmployeeRecord> employeeMap) {
        
        // Find the employee
        EmployeeRecord employee = employeeMap.get(employeeId);
        if (employee == null) return;
        
        // Create employee div
        html.append("                <div class=\"employee level-").append(level).append("\">\n");
        html.append("                    <span class=\"employee-name\">").append(escapeHtml(employee.getName())).append("</span>\n");
        html.append("                    <span class=\"employee-id\">(ID: ").append(employee.getID()).append(")</span>\n");
        
        // Add badges
        if (level == 0) {
            html.append("                    <span class=\"ceo-badge\">CEO</span>\n");
        } else if (hierarchyTree.containsKey(employeeId) && !hierarchyTree.get(employeeId).isEmpty()) {
            html.append("                    <span class=\"manager-badge\">Manager</span>\n");
        }
        
        html.append("                </div>\n");
        
        // Add children
        if (hierarchyTree.containsKey(employeeId)) {
            for (EmployeeRecord child : hierarchyTree.get(employeeId)) {
                generateHierarchyHTML(hierarchyTree, child.getID(), level + 1, html, employeeMap);
            }
        }
    }
    

    
    private int calculateMaxLevel(Map<String, List<EmployeeRecord>> hierarchyTree, String ceoId) {
        return calculateMaxLevelRecursive(hierarchyTree, ceoId, 0);
    }
    
    private int calculateMaxLevelRecursive(Map<String, List<EmployeeRecord>> hierarchyTree, 
                                         String employeeId, int currentLevel) {
        if (!hierarchyTree.containsKey(employeeId)) {
            return currentLevel;
        }
        
        int maxLevel = currentLevel;
        for (EmployeeRecord child : hierarchyTree.get(employeeId)) {
            int childLevel = calculateMaxLevelRecursive(hierarchyTree, child.getID(), currentLevel + 1);
            maxLevel = Math.max(maxLevel, childLevel);
        }
        
        return maxLevel;
    }
    
    private String escapeHtml(String text) {
        if (text == null) return "";
        return text.replace("&", "&amp;")
                   .replace("<", "&lt;")
                   .replace(">", "&gt;")
                   .replace("\"", "&quot;")
                   .replace("'", "&#39;");
    }
    
    @Override
    public String getFileExtension() {
        return "html";
    }
    
    @Override
    public String getMimeType() {
        return "text/html";
    }
    
    @Override
    public String getFormatterName() {
        return "HTML";
    }
} 